

/* */
/* DETAIL */
DATA DETAIL;
INPUT 
    DATE DATE9.
    AREACODE
    PHONENUM $8.
    TOACRONYM $
    FROMACRONYM $
    SECRETCODE
;
FORMAT 
    DATE YYMMDD10.
;
DATALINES;
21DEC2006 407 312-9088 AFAIK DQMOT 103
21DEC2006 407 324-6674 BEG TU 101
21DEC2006 407 312-9088 BFN SYS 101
21DEC2006 407 312-9088 BTDT IHU 102
22DEC2006 407 312-9088 C&G AFAIK 103
;

PROC PRINT DATA = DETAIL;
RUN;


/* */
/* LOOKUP_1 */
DATA LOOKUP_1;
INPUT 
    ACRONYM $
    MEANING $30.
;
DATALINES;
AFAIK AS FAR AS I KNOW
AFK AWAY FROM KEYBOARD
ASAP AS SOON AS POSSIBLE
BEG BIG EVIL GRIN
BFN BYE FOR NOW
BTDT BEEN THERE, DONE THAT
DQMOT DON'T QUOTE ME ON THIS.
IHU I HATE YOU
SYS SEE YOU SOON
;

PROC PRINT DATA = LOOKUP_1;
RUN;


/* */
/* 
    --F1--
    MERGE 
*/
PROC SORT 
    DATA = DETAIL 
    OUT = _T1 
NODUPKEY;
BY TOACRONYM;
RUN;

PROC SORT 
    DATA = LOOKUP_1 
    OUT = _T2(
        RENAME = (
            ACRONYM = TOACRONYM
            MEANING = TOMEANING
        )
    )
NODUPKEY;
BY ACRONYM;
RUN;

DATA T;
MERGE _T1(IN=A) _T2(IN=B);
BY TOACRONYM;
IF A;
RUN;

PROC DELETE DATA = _T1 _T2;
RUN;

PROC PRINT DATA = T;
RUN;


/* */
/* 
    --F2--
    SQL 
*/
PROC SQL;
SELECT 
    A.*,
    B.MEANING AS TOMEANING
FROM DETAIL AS A LEFT JOIN LOOKUP_1 AS B
ON A.TOACRONYM = B.ACRONYM
;
QUIT;


/* */
/* 
    --F3--
    HASH (RIGHT) 
*/
DATA RESULTS;
IF 0 THEN SET LOOKUP_1;
DROP ACRONYM MEANING RC;
IF _N_ = 1 THEN DO;
    DECLARE HASH HASHLOOKUP(DATASET:'LOOKUP_1');
    HASHLOOKUP.DEFINEKEY('ACRONYM');
    HASHLOOKUP.DEFINEDATA('MEANING');
    HASHLOOKUP.DEFINEDONE();
    CALL MISSING(ACRONYM, MEANING);
END;
SET DETAIL;
RC = HASHLOOKUP.FIND(KEY:TOACRONYM);
IF RC = 0 THEN TOMEANING = MEANING;
RUN; 

PROC PRINT DATA = RESULTS;
RUN;


/* */
DATA _R1;
/* IF 0 THEN SET LOOKUP_1; */
DROP ACRONYM MEANING RC;
IF _N_ = 1 THEN DO;
    DECLARE HASH HASHLOOKUP(DATASET:'LOOKUP_1');
    HASHLOOKUP.DEFINEKEY('ACRONYM');
    HASHLOOKUP.DEFINEDATA('MEANING');
    HASHLOOKUP.DEFINEDONE();
    CALL MISSING(ACRONYM, MEANING);
END;
SET DETAIL;
RC = HASHLOOKUP.FIND(KEY:TOACRONYM);
IF RC = 0 THEN TOMEANING = MEANING;
RUN; 

PROC PRINT DATA = _R1;
RUN;


/* */
/* 
    HASH ERROR2
*/
DATA _R2;
IF 0 THEN SET LOOKUP_1;
DROP ACRONYM MEANING RC;
IF _N_ = 1 THEN DO;
    DECLARE HASH HASHLOOKUP(DATASET:'LOOKUP_1');
    HASHLOOKUP.DEFINEKEY('ACRONYM');
    HASHLOOKUP.DEFINEDATA('MEANING');
    HASHLOOKUP.DEFINEDONE();
/*     CALL MISSING(ACRONYM, MEANING); */
END;
SET DETAIL;
RC = HASHLOOKUP.FIND(KEY:TOACRONYM);
IF RC = 0 THEN TOMEANING = MEANING;
RUN; 

PROC PRINT DATA = _R2;
RUN;


/* */
/* 
    HASH ERROR3
*/
DATA _R3;
IF 0 THEN SET LOOKUP_1;
DROP ACRONYM MEANING RC;
IF _N_ = 1 THEN DO;
    DECLARE HASH HASHLOOKUP(DATASET:'LOOKUP_1');
    HASHLOOKUP.DEFINEKEY('ACRONYM');
    HASHLOOKUP.DEFINEDATA('MEANING');
    HASHLOOKUP.DEFINEDONE();
    CALL MISSING(ACRONYM, MEANING);
END;
SET DETAIL;
RC = HASHLOOKUP.FIND(KEY:TOACRONYM);
TOMEANING = MEANING;
RUN; 

PROC PRINT DATA = _R3;
RUN;
